/**
 * LLM stub — mimics the @google/genai Gemini structured-output API.
 *
 * PROVIDED — do not edit this file.
 *
 * Behavior:
 *   - Reads LLM_API_VERSION from env ('v1' default, 'v2' for the debugging scenario).
 *   - v1 returns the canonical EvaluationResult shape.
 *   - v2 returns a DIFFERENT shape (relevant to Part 2 / incident-2.log).
 *   - ~15% of calls return malformed JSON, deterministically keyed by contactId.
 *   - Always returns usageMetadata with token counts.
 */

import type { EvaluationResult } from '../types/evaluation.js'

export interface LlmUsageMetadata {
  promptTokenCount: number
  candidatesTokenCount: number
}

export interface LlmResponse {
  text: string
  usageMetadata: LlmUsageMetadata
  modelVersion: string
}

function hashContactId(contactId: string): number {
  let h = 0
  for (let i = 0; i < contactId.length; i++) {
    h = (Math.imul(31, h) + contactId.charCodeAt(i)) | 0
  }
  return Math.abs(h)
}

function buildV1Result(contactId: string): EvaluationResult {
  const seed = hashContactId(contactId)
  return {
    overallScore: 5 + (seed % 50) / 10,
    categories: [
      { name: 'empathy', score: 4 + (seed % 60) / 10, feedback: 'Agent showed good empathy.' },
      { name: 'resolution', score: 6 + (seed % 40) / 10, feedback: 'Issue resolved on first contact.' },
    ],
    summary: `Call handled adequately. Contact ID: ${contactId}.`,
    flags: seed % 7 === 0 ? ['escalation-risk'] : [],
  }
}

function buildV2Result(contactId: string): Record<string, unknown> {
  const v1 = buildV1Result(contactId)
  return {
    result: {
      score: v1.overallScore,
      categories: v1.categories,
      summary: v1.summary,
      flags: v1.flags,
    },
  }
}

function buildUsageMetadata(version: string, contactId: string): LlmUsageMetadata {
  const seed = hashContactId(contactId)
  const prompt = 800 + (seed % 400)
  const completion = 200 + (seed % 150)

  if (version === 'v2') {
    return {
      promptTokens: prompt,
      completionTokens: completion,
    } as unknown as LlmUsageMetadata
  }

  return {
    promptTokenCount: prompt,
    candidatesTokenCount: completion,
  }
}

export async function callLlm(params: {
  systemPrompt: string
  transcript: string
  contactId: string
}): Promise<LlmResponse> {
  const version = process.env.LLM_API_VERSION ?? 'v1'
  const modelName = process.env.LLM_MODEL_NAME ?? 'gemini-1.5-pro'
  const modelVersion = `${modelName}@${version}`

  const seed = hashContactId(params.contactId)
  const isMalformed = seed % 20 < 3

  let text: string

  if (isMalformed) {
    const partial = JSON.stringify(buildV1Result(params.contactId))
    text = partial.slice(0, partial.length - 20) + '...'
  } else if (version === 'v2') {
    text = JSON.stringify(buildV2Result(params.contactId))
  } else {
    text = JSON.stringify(buildV1Result(params.contactId))
  }

  return {
    text,
    usageMetadata: buildUsageMetadata(version, params.contactId),
    modelVersion,
  }
}
