/**
 * Prompt store stub — mimics loading LLM prompts from an S3 JSON tree.
 *
 * PROVIDED — do not edit this file.
 *
 * In production, prompts live in S3 under a JSON tree keyed by path.
 * This stub loads them from the local fixtures/prompts/ directory and
 * caches the full tree for 5 minutes, mirroring the production TTL pattern.
 *
 * Usage:
 *   const prompt = await getPrompt('coaching-evaluation')
 */

import fs from 'node:fs/promises'
import path from 'node:path'

const TTL_MS = 5 * 60 * 1000  // 5 minutes

interface Cache {
  tree: Record<string, string>
  fetchedAt: number
}

let cache: Cache | null = null

async function loadTree(): Promise<Record<string, string>> {
  const dir = path.resolve(process.cwd(), 'fixtures', 'prompts')
  const files = await fs.readdir(dir)
  const entries = await Promise.all(
    files
      .filter(f => f.endsWith('.json'))
      .map(async f => {
        const raw = await fs.readFile(path.join(dir, f), 'utf-8')
        const key = f.replace(/\.json$/, '')
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const parsed = JSON.parse(raw)
        return [key, typeof parsed === 'string' ? parsed : (parsed as { prompt: string }).prompt] as const
      }),
  )
  return Object.fromEntries(entries)
}

export async function getPrompt(promptKey: string): Promise<string> {
  const now = Date.now()

  if (!cache || now - cache.fetchedAt > TTL_MS) {
    const tree = await loadTree()
    cache = { tree, fetchedAt: now }
    console.info('[promptStore] cache refreshed')
  }

  const prompt = cache.tree[promptKey]
  if (!prompt) {
    throw new Error(`[promptStore] prompt not found: ${promptKey}`)
  }
  return prompt
}
