/**
 * SSM Parameter Store helper — runtime parameter fetch.
 *
 * PROVIDED — do not edit this file.
 *
 * In production this is used to fetch values that must change without a redeploy
 * (e.g. the active LLM model name). Secrets baked at deploy time (DB password,
 * ES credentials) use ${ssm:...} substitution in serverless.env.yml instead.
 *
 * For local development: if the target env var is already set (e.g. LLM_MODEL_NAME
 * in .env), the SSM call is skipped automatically.
 */

import { SSMClient, GetParameterCommand } from '@aws-sdk/client-ssm'

const ssmClient = new SSMClient({ region: process.env.AWS_REGION ?? 'us-east-1' })

/**
 * Fetch a parameter from SSM Parameter Store at runtime.
 * Falls back to the provided envFallback if running locally (env var already set).
 */
export async function getParameter(
  paramPath: string,
  envFallback?: string,
): Promise<string> {
  if (envFallback && process.env[envFallback]) {
    return process.env[envFallback] as string
  }

  const command = new GetParameterCommand({
    Name: paramPath,
    WithDecryption: false,
  })

  const response = await ssmClient.send(command)
  const value = response.Parameter?.Value

  if (!value) {
    throw new Error(`[ssm] Parameter not found or empty: ${paramPath}`)
  }

  return value
}

/**
 * Returns the active LLM model name.
 * Fetched at runtime so it can change without a Lambda redeploy.
 */
export async function getLlmModelName(): Promise<string> {
  const stage = process.env.STAGE ?? 'dev'
  return getParameter(`/companyx-${stage}/llm_model_name`, 'LLM_MODEL_NAME')
}
