/**
 * Smoke tests for PROVIDED modules only.
 * These pass against the unmodified scaffold.
 *
 * PROVIDED — do not edit this file.
 * Add your own tests in a separate file if you want to verify your implementation.
 */

import { describe, it, expect } from 'vitest'
import { EvaluationResultSchema } from '../src/types/evaluation.js'
import { StructuredOutputError, FatalIngestError } from '../src/types/errors.js'
import { callLlm } from '../src/services/llm-stub.js'

describe('EvaluationResultSchema', () => {
  it('accepts a valid v1 evaluation result', () => {
    const valid = {
      overallScore: 7.5,
      categories: [{ name: 'empathy', score: 8, feedback: 'Great empathy shown.' }],
      summary: 'Good call overall.',
      flags: [],
    }
    expect(() => EvaluationResultSchema.parse(valid)).not.toThrow()
  })

  it('rejects a result missing overallScore', () => {
    const invalid = {
      categories: [{ name: 'empathy', score: 8, feedback: 'Great.' }],
      summary: 'Good.',
      flags: [],
    }
    expect(() => EvaluationResultSchema.parse(invalid)).toThrow()
  })

  it('rejects overallScore outside 0-10', () => {
    const invalid = { overallScore: 11, categories: [{ name: 'x', score: 5, feedback: 'y' }], summary: 'z', flags: [] }
    expect(() => EvaluationResultSchema.parse(invalid)).toThrow()
  })
})

describe('Error classes', () => {
  it('StructuredOutputError carries contactId and rawResponse', () => {
    const err = new StructuredOutputError('bad json', 'contact-001', '{"broken":')
    expect(err.name).toBe('StructuredOutputError')
    expect(err.contactId).toBe('contact-001')
    expect(err.rawResponse).toBe('{"broken":')
    expect(err).toBeInstanceOf(Error)
  })

  it('FatalIngestError carries cause', () => {
    const cause = new Error('s3 timeout')
    const err = new FatalIngestError('S3 download failed', cause)
    expect(err.name).toBe('FatalIngestError')
    expect(err.cause).toBe(cause)
    expect(err).toBeInstanceOf(Error)
  })
})

describe('LLM stub', () => {
  it('returns a response object with required fields for contactId', async () => {
    const result = await callLlm({
      systemPrompt: 'evaluate this',
      transcript: 'Customer called about billing.',
      contactId: 'contact-002',  // deterministically returns valid JSON for this contactId
    })
    expect(result).toHaveProperty('text')
    expect(result).toHaveProperty('usageMetadata')
    expect(result).toHaveProperty('modelVersion')
    expect(typeof result.text).toBe('string')
  })

  it('returns deterministic results for the same contactId', async () => {
    const params = { systemPrompt: 'eval', transcript: 'test', contactId: 'contact-007' }
    const r1 = await callLlm(params)
    const r2 = await callLlm(params)
    expect(r1.text).toBe(r2.text)
  })
})
