/**
 * Local trigger — invokes the ingest handler with a fake S3Event.
 *
 * PROVIDED — do not edit this file.
 *
 * Usage:
 *   pnpm trigger:local [path/to/csv]
 *   pnpm trigger:local fixtures/transcripts.csv
 *
 * Prerequisites:
 *   docker compose up -d   (Elasticsearch must be running)
 *   cp .env.example .env   (env vars must be set)
 *
 * S3 is mocked from disk — no AWS credentials required.
 */

import 'dotenv/config'
import fs from 'node:fs'
import path from 'node:path'
import { mockClient } from 'aws-sdk-client-mock'
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3'
import { sdkStreamMixin } from '@aws-sdk/util-stream-node'
import type { S3Event, S3EventRecord } from 'aws-lambda'
// aws-sdk-client-mock patches S3Client.prototype.send, so this import
// is safe before mock.on() calls — all instances share the patched prototype.
import { handler } from '../src/handlers/ingest.js'

async function main(): Promise<void> {
  const csvPath = path.resolve(process.cwd(), process.argv[2] ?? 'fixtures/transcripts.csv')

  if (!fs.existsSync(csvPath)) {
    console.error(`[trigger-local] File not found: ${csvPath}`)
    process.exit(1)
  }

  const s3Mock = mockClient(S3Client)
  s3Mock.on(GetObjectCommand).resolves({
    Body: sdkStreamMixin(fs.createReadStream(csvPath)) as never,
    ContentLength: fs.statSync(csvPath).size,
  })

  const bucket = process.env.INGEST_BUCKET ?? 'companyx-ingest-tenant-a-dev'
  const key = `exports/${new Date().toISOString().slice(0, 10)}/${path.basename(csvPath)}`

  const record: S3EventRecord = {
    eventVersion: '2.1',
    eventSource: 'aws:s3',
    awsRegion: process.env.AWS_REGION ?? 'us-east-1',
    eventTime: new Date().toISOString(),
    eventName: 'ObjectCreated:Put',
    userIdentity: { principalId: 'local' },
    requestParameters: { sourceIPAddress: '127.0.0.1' },
    responseElements: { 'x-amz-request-id': 'local', 'x-amz-id-2': 'local' },
    s3: {
      s3SchemaVersion: '1.0',
      configurationId: 'local',
      bucket: {
        name: bucket,
        ownerIdentity: { principalId: 'local' },
        arn: `arn:aws:s3:::${bucket}`,
      },
      object: {
        key,
        size: fs.statSync(csvPath).size,
        eTag: 'local',
        sequencer: 'local',
      },
    },
  }

  const event: S3Event = { Records: [record] }

  console.info('[trigger-local] invoking handler')
  console.info(`[trigger-local] bucket=${bucket} key=${key}`)

  try {
    const result = await handler(event)
    console.info('[trigger-local] handler completed successfully')
    console.info(JSON.stringify(result, null, 2))
  } catch (err) {
    console.error('[trigger-local] handler threw:', err)
    process.exit(1)
  }
}

main().catch((err: unknown) => {
  console.error(err)
  process.exit(1)
})
